### ISSUE TITLE
showDatePickerDialog crash the app

### ISSUE THREAD

**Issue by PietroGranati** [viezel/NappDrawer#181]
I've always used showDatePickerDialog and works, when I add the menu and try to call that an error occurs:

[ERROR] :  TiApplication: (KrollRuntimeThread) [1774,1774] Sending event: exception on thread: KrollRuntimeThread msg:android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.; Titanium 4.1.0,2015/07/06 11:15,d57aa7d
[ERROR] :  TiApplication: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6264)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:871)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:361)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.View.requestLayout(View.java:17454)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.addView(ViewGroup.java:3732)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.addView(ViewGroup.java:3710)
[ERROR] :  TiApplication: 	at android.support.v7.widget.Toolbar.addSystemView(Toolbar.java:1034)
[ERROR] :  TiApplication: 	at android.support.v7.widget.Toolbar.ensureMenuView(Toolbar.java:846)
[ERROR] :  TiApplication: 	at android.support.v7.widget.Toolbar.setMenu(Toolbar.java:377)
[ERROR] :  TiApplication: 	at android.support.v7.internal.widget.ToolbarWidgetWrapper.setMenu(ToolbarWidgetWrapper.java:414)
[ERROR] :  TiApplication: 	at android.support.v7.internal.widget.ActionBarOverlayLayout.setMenu(ActionBarOverlayLayout.java:780)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1083)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1374)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:126)
[ERROR] :  TiApplication: 	at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:211)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)

**Comment by PietroGranati** [comment]
Same for me! Please fix!
