### ISSUE TITLE
App crashes when setRightWindow only

### ISSUE THREAD

**Issue by ehab88** [viezel/NappDrawer#206]
[ERROR] :  TiApplication: (main) [1327,4879] Sending event: exception on thread: main msg:java.lang.NullPointerException; Titanium 6.2.2,2017/09/19 16:01,undefined
[ERROR] :  TiApplication: java.lang.NullPointerException
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewBehind.getSecondaryBehindWidth(CustomViewBehind.java:80)
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewBehind.scrollBehindTo(CustomViewBehind.java:251)
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewAbove.scrollTo(CustomViewAbove.java:805)
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewAbove.onSizeChanged(CustomViewAbove.java:467)
[ERROR] :  TiApplication: 	at android.view.View.setFrame(View.java:14094)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14006)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
[ERROR] :  TiApplication: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14008)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14008)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1711)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
[ERROR] :  TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:532)
[ERROR] :  TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
[ERROR] :  TiApplication: 	at android.os.Handler.handleCallback(Handler.java:725)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:92)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:137)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5041)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Max87ZA** [comment]
I've got this bug too with same errors. Please look at it soon. Thanks

**Comment by qasim90** [comment]
I am getting this too. Any workarounds?

**Comment by Max87ZA** [comment]
I had to create leftMenu, no workarounds possible so far. We have to wait for developer to fix this...

**Comment by qasim90** [comment]
I think this fixes it ( at least on android, not checked on iOS so far):
`leftWindow : OS_IOS? Ti.UI.createWindow() : Ti.UI.createView()`

**Comment by Max87ZA** [comment]
Yes, you have to create window/view and assign it to leftWindow to make it work. If I remeber correctly, this bug is Android only(If I'm wrong, sorry)...
