### ISSUE TITLE
How can add nappdrawer to tab in tabgroup on android ?

### ISSUE THREAD

**Issue by kimnamcham** [viezel/NappDrawer#87]
On ios is ok, but on android it crashed. Somebody can help me? thanks

[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40ce01f8)
[ERROR] :  TiApplication: (main) [8244,13369] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ios.xoso.bongda/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: Windows are created during open; Titanium 3.2.2,2014/03/05 12:22,96e9a07
[ERROR] :  TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ios.xoso.bongda/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: Windows are created during open
[ERROR] :  TiApplication:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
[ERROR] :  TiApplication:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
[ERROR] :  TiApplication:   at android.app.ActivityThread.access$600(ActivityThread.java)
[ERROR] :  TiApplication:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
[ERROR] :  TiApplication:   at android.os.Handler.dispatchMessage(Handler.java)
[ERROR] :  TiApplication:   at android.os.Looper.loop(Looper.java)
[ERROR] :  TiApplication:   at android.app.ActivityThread.main(ActivityThread.java)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
[ERROR] :  TiApplication:   at dalvik.system.NativeStart.main(Native Method)
[ERROR] :  TiApplication: Caused by: java.lang.IllegalStateException: Windows are created during open
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiWindowProxy.createView(TiWindowProxy.java:80)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:463)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:449)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.widget.tabgroup.TiUIAbstractTab.getContentView(TiUIAbstractTab.java:58)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.widget.tabgroup.TiUIActionBarTab.initializeFragment(TiUIActionBarTab.java:92)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.widget.tabgroup.TiUIActionBarTabGroup.onTabSelected(TiUIActionBarTabGroup.java:127)
[ERROR] :  TiApplication:   at com.android.internal.app.ActionBarImpl.selectTab(ActionBarImpl.java)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.widget.tabgroup.TiUIActionBarTabGroup.selectTab(TiUIActionBarTabGroup.java:102)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.TabGroupProxy.handlePostOpen(TabGroupProxy.java:352)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.TabGroupProxy.windowCreated(TabGroupProxy.java:319)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:452)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:528)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication:   at android.app.Activity.performCreate(Activity.java)
[ERROR] :  TiApplication:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
[ERROR] :  TiApplication:   ... 12 more

**Comment by mansoulx** [comment]
@shodanuk would you like to share your "mimicced" tabGroup please ?!
